// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS2UAxEySLYN5F0tCgXly6xhsABRX2yII',
    appId: '1:1022141928653:web:0b35e10a45375a98db4584',
    messagingSenderId: '1022141928653',
    projectId: 'fruits-shop-app',
    authDomain: 'fruits-shop-app.firebaseapp.com',
    storageBucket: 'fruits-shop-app.firebasestorage.app',
    measurementId: 'G-9F3MVC2TBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYc9_Zq3_yWJX5cXRa1dDbY9Vpi03nCdM',
    appId: '1:1022141928653:android:334969ae93c79a54db4584',
    messagingSenderId: '1022141928653',
    projectId: 'fruits-shop-app',
    storageBucket: 'fruits-shop-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKk9XY2nIB7XS_BgRdYzCmcTwKHFU-SFQ',
    appId: '1:1022141928653:ios:16b7786b4f5acea6db4584',
    messagingSenderId: '1022141928653',
    projectId: 'fruits-shop-app',
    storageBucket: 'fruits-shop-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKk9XY2nIB7XS_BgRdYzCmcTwKHFU-SFQ',
    appId: '1:1022141928653:ios:16b7786b4f5acea6db4584',
    messagingSenderId: '1022141928653',
    projectId: 'fruits-shop-app',
    storageBucket: 'fruits-shop-app.firebasestorage.app',
    iosBundleId: 'com.example.fruitsECommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS2UAxEySLYN5F0tCgXly6xhsABRX2yII',
    appId: '1:1022141928653:web:2c8616c6c75663eddb4584',
    messagingSenderId: '1022141928653',
    projectId: 'fruits-shop-app',
    authDomain: 'fruits-shop-app.firebaseapp.com',
    storageBucket: 'fruits-shop-app.firebasestorage.app',
    measurementId: 'G-WH9E8VRQMY',
  );

}